# Generated by Django 5.0.6 on 2024-06-21 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='fotoverificacao',
            name='caminho_arquivo',
        ),
        migrations.AddField(
            model_name='fotoverificacao',
            name='imagem',
            field=models.ImageField(default='verificacoes/default.png', upload_to='verificacoes/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem_presente', models.ImageField(blank=True, null=True, upload_to='presentes/')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postocombustivel')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('desconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.desconto')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localizacao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
