# Generated by Django 5.0.6 on 2024-06-26 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comentario_usuario_alter_avaliacao_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='borracharia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.borracharia'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='oficina_mecanica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.oficinamecanica'),
        ),
        migrations.AddField(
            model_name='desconto',
            name='condicoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desconto',
            name='pontos_necessarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desconto',
            name='requer_pontos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desconto',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotoverificacao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotoverificacao',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.postocombustivel'),
        ),
        migrations.AlterField(
            model_name='fotoverificacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='verificacoes/'),
        ),
        migrations.CreateModel(
            name='PontuacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
