# Generated by Django 5.0.6 on 2024-07-03 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avaliacao_borracharia_avaliacao_oficina_mecanica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_combustivel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.postocombustivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
