# Generated by Django 5.0.6 on 2024-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicoabastecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='avaliacao',
            field=models.IntegerField(default=3),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('elogio', 'Elogio'), ('sugestao', 'Sugestão'), ('reclamacao', 'Reclamação')], default='elogio', max_length=10),
            preserve_default=True,
        ),
    ]
