# Generated by Django 5.0.6 on 2024-07-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comentario_avaliacao_comentario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='avaliacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('elogio', 'Elogio'), ('sugestao', 'Sugestão'), ('reclamacao', 'Reclamação')], max_length=10),
        ),
    ]
