# Generated by Django 5.0.6 on 2024-07-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_postocombustivel_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
