# Generated by Django 5.0.6 on 2024-07-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comentario_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='borracharia',
        ),
        migrations.RemoveField(
            model_name='codigodesconto',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='codigodesconto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='desconto',
            name='posto',
        ),
        migrations.RemoveField(
            model_name='fotoverificacao',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='fotoverificacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='oficinamecanica',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='oficina_mecanica',
        ),
        migrations.RemoveField(
            model_name='pontuacaousuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Borracharia',
        ),
        migrations.DeleteModel(
            name='CodigoDesconto',
        ),
        migrations.DeleteModel(
            name='Desconto',
        ),
        migrations.DeleteModel(
            name='FotoVerificacao',
        ),
        migrations.DeleteModel(
            name='OficinaMecanica',
        ),
        migrations.DeleteModel(
            name='PontuacaoUsuario',
        ),
    ]
